version: '3.9'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: yp_es
    env_file:
      - ./postgres_to_es/.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elsticsearch/data
    ports:
      - "9200:9200"
    networks:
      - yp_network

  etl:
    build:
      context: ./postgres_to_es
      dockerfile: Dockerfile
      args:
        uid: ${HOST_UID}
        gid: ${HOST_GID}
    container_name: yp_etl
    user: "devuser"
#    command: tail -f /dev/null
    command: python3 etl.py
    env_file:
      - ./postgres_to_es/.env
    restart: always
    volumes:
      - ./postgres_to_es:/usr/src/postgres_to_es
    networks:
      - yp_network
    depends_on:
      - es

volumes:
  es-data:

networks:
  yp_network:
    name: yp_network
    external: true
