version: '3.9'
services:

  db:
    build:
      context: https://github.com/merkushov/Admin_panel_sprint_2.git#main:services/postgresql
      dockerfile: Dockerfile
    container_name: yandex_p_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - yandex_p_network

  app:
    build:
      context: https://github.com/merkushov/Admin_panel_sprint_2.git#main:movies_admin
      dockerfile: Dockerfile.prod
    container_name: yandex_p_app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    env_file:
      - .env
    volumes:
      - static_volume:/usr/src/app/static
    networks:
      - yandex_p_network
    depends_on:
      - db

  nginx:
    build:
      context: https://github.com/merkushov/Admin_panel_sprint_2.git#main:services/nginx
      dockerfile: Dockerfile.prod
    container_name: yandex_p_nginx
    volumes:
      - static_volume:/usr/src/app/static
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - yandex_p_network

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: yandex_p_es
    env_file:
      - ./postgres_to_es/.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elsticsearch/data
    networks:
      - yandex_p_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: yandex_p_kib
    env_file:
      - ./postgres_to_es/.env
    ports:
      - "5601:5601"
    networks:
      - yandex_p_network
    depends_on:
      - es

  etl:
    build:
      context: ./postgres_to_es
      dockerfile: Dockerfile
      args:
        uid: ${HOST_UID}
        gid: ${HOST_GID}
    container_name: yandex_p_etl
    user: "devuser"
    command: tail -f /dev/null
    # command: python3 etl.py
    env_file:
      - ./postgres_to_es/.env
    restart: always
    volumes:
      - ./postgres_to_es:/usr/src/postgres_to_es
    networks:
      - yandex_p_network
    depends_on:
      - db
      - es

volumes:
  postgres-data:
  static_volume:
  es-data:

networks:
  yandex_p_network: