version: '3.9'
services:

  db:
    build:
      context: ./movies_admin
      dockerfile: Dockerfile.database
    container_name: yandex_p_db
    restart: always
    env_file:
      - ./movies_admin/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - yandex_p_network

  app:
    build:
      context: ./movies_admin
      dockerfile: Dockerfile
    container_name: yandex_p_app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./movies_admin/.env
    volumes:
      - ./movies_admin:/usr/src/app
      - static_volume:/usr/src/app/static
    expose:
      - "8000"
    networks:
      - yandex_p_network
    depends_on:
      - db

  nginx:
    image: nginx:1.19.2
    container_name: yandex_p_nginx
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/sites:/etc/nginx/conf.d:ro
      - static_volume:/usr/src/app/static
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - yandex_p_network

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: yandex_p_es
    env_file:
      - ./postgres_to_es/.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elsticsearch/data
    expose:
      - "9200"
    networks:
      - yandex_p_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: yandex_p_kib
    env_file:
      - ./postgres_to_es/.env
    ports:
      - "5601:5601"
    networks:
      - yandex_p_network
    depends_on:
      - es

  etl:
    build:
      context: ./postgres_to_es
      dockerfile: Dockerfile
    container_name: yandex_p_etl
#    command: tail -f /dev/null
    command: python3 etl.py
    env_file:
      - ./postgres_to_es/.env
    restart: always
    volumes:
      - ./postgres_to_es:/usr/src/postgres_to_es
    networks:
      - yandex_p_network
    depends_on:
      - db
      - es

volumes:
  postgres-data:
  static_volume:
  es-data:

networks:
  yandex_p_network: