FROM python:3.9

RUN apt-get update
RUN apt-get install -y gettext

# set work directory
WORKDIR /usr/src/app

COPY requirements ./requirements
RUN pip install --upgrade pip
RUN pip install -r ./requirements/production.txt

# copy project
COPY . .

CMD ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000"]